platform :ios, '9.0'
use_frameworks!

target 'SmartAd_Example' do
    pod 'SmartAd', :path => '../'

    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/AdMob'
    pod 'FBAudienceNetwork'
end
